-- CreateTable
CREATE TABLE "usuarios" (
    "id" SERIAL NOT NULL,
    "ids" TEXT DEFAULT '',
    "user_id" TEXT DEFAULT '',
    "nome" TEXT DEFAULT '',
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "senha" TEXT DEFAULT '',
    "telefone" TEXT DEFAULT '',
    "cpf" TEXT DEFAULT '',
    "firstname" TEXT DEFAULT '',
    "lastname" TEXT DEFAULT '',
    "user_company" TEXT DEFAULT '',
    "user_name" TEXT DEFAULT '',
    "user_register" TEXT DEFAULT '',
    "user_password" TEXT DEFAULT '',
    "user_mail" TEXT DEFAULT '',
    "user_phone" TEXT DEFAULT '',
    "user_cpf" TEXT DEFAULT '',
    "user_pos_id" TEXT DEFAULT '',
    "user_levelaccess" TEXT DEFAULT '',
    "user_acreditacion" TEXT DEFAULT '',
    "user_apikeymobile" TEXT DEFAULT '',
    "user_servername" TEXT DEFAULT '',
    "user_devicestatus" TEXT DEFAULT '',
    "user_keyprivate" TEXT DEFAULT '',
    "user_apikeyhardware" TEXT DEFAULT '',
    "user_apikeysoftware" TEXT DEFAULT '',
    "user_messages" TEXT DEFAULT '',
    "user_passwordremote" TEXT DEFAULT '',
    "user_groupusers" TEXT DEFAULT '',
    "user_issync" TEXT DEFAULT '',
    "user_uniqueid" TEXT DEFAULT '',
    "user_vpa_id" TEXT DEFAULT '',
    "user_key" TEXT DEFAULT '',
    "user_name_register" TEXT DEFAULT '',
    "user_status" TEXT DEFAULT '',
    "user_locked" TEXT DEFAULT '',
    "user_key_hardware" TEXT DEFAULT '',
    "user_level_access" TEXT DEFAULT '0',
    "user_vpa" TEXT NOT NULL,
    "user_token" TEXT DEFAULT '',
    "user_public_key" TEXT DEFAULT '',
    "user_private_key" TEXT DEFAULT '',
    "user_wallet_id" TEXT DEFAULT '',
    "user_system_type" TEXT DEFAULT '',
    "user_mail_verify" TEXT DEFAULT '',
    "user_phone_verify" TEXT DEFAULT '',
    "user_professional_type" TEXT DEFAULT '',
    "user_gender" TEXT DEFAULT '',
    "user_born_date" TEXT DEFAULT '',
    "user_nation" TEXT DEFAULT '',
    "user_photo_ci" TEXT DEFAULT '',
    "user_photo" TEXT DEFAULT '',
    "user_bank_name" TEXT DEFAULT '',
    "user_bank_user_name" TEXT DEFAULT '',
    "user_bank_account" TEXT DEFAULT '',
    "user_bank_agency" TEXT DEFAULT '',
    "user_bank_user_cpf" TEXT DEFAULT '',
    "user_date_register" TEXT DEFAULT '',
    "user_otp_verify" TEXT DEFAULT '',
    "user_latitude" TEXT DEFAULT '',
    "user_longitude" TEXT DEFAULT '',
    "user_coordinates" TEXT DEFAULT '',
    "user_number_services" TEXT DEFAULT '',
    "Status" TEXT DEFAULT '',
    "servicos" TEXT DEFAULT '',
    "user_issinc" TEXT DEFAULT '',
    "counter" INTEGER DEFAULT 0,

    CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "usuarios_email_key" ON "usuarios"("email");

-- CreateIndex
CREATE UNIQUE INDEX "usuarios_user_vpa_key" ON "usuarios"("user_vpa");
