version: '3.8'

services:
  postgres: 
    image: postgres:14
    container_name: postgresn
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ~/postgres:/var/lib/postgresql/data  
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}  

##  mongodb:
##      image: mongo:latest
##      container_name: mongodbn
##      restart: unless-stopped
##      env_file:
##        - .env
##      environment:
##  #      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
##  #      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}    
##  #      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
##  #      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
##         - MONGO_INITDB_DATABASE=${MONGO_DB}
##         - PUID=1000
##         - PGID=1000
##      ports:
##        - ${MONGO_INT_PORT}:${MONGO_EXT_PORT}
##      volumes:
##        - ./mongodb/database:/data/db
##        - ./.docker/mongo/:/docker-entrypoint-initdb.d/:ro
##
##  mongo-express:
##    image: mongo-express
##    container_name: mongoexpress
##    restart: unless-stopped
##    env_file:
##      - .env
##    ports:
##      - ${ME_INT_PORT}:${ME_EXT_PORT}
##    environment:
##      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER} #db docker / localhost local-running
##      - ME_CONFIG_MONGODB_AUTH_USERNAME=${ME_CONFIG_MONGODB_AUTH_USERNAME}
##      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${ME_CONFIG_MONGODB_AUTH_PASSWORD}
##      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
##      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
##      - ME_CONFIG_MONGODB_URL=mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@mongo:27017/?authSource=admin
##    depends_on:
##      - mongodb
##    links:
##      - mongodb
##

volumes:
  postgres:
    name: server-db-posgres
##  mongodb:
##    name: server-db-mongo
##  mongo-express:
##    name: server-db-mongo-express  