export enum ERole {
  User = 'user',
  Admin = 'admin',
  Moderator = 'moderator',
  VPA = 'VPA',
  FRIGORIFICO = 'FRIGORIFICO',
  PROPIEDAD = 'PROPIEDAD',
  PRODUCTOR = 'PRODUCTOR',
  SENACSA = 'SENACSA',
  SITRAP = 'SITRAP',
  ASSOCIACION = 'ASSOCIACION',
  PUESTOCONTROL = 'PUESTOCONTROL',
  GERENTE = 'GERENTE',
  UNDEFINED = '----',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  CLIENT = 'CLIENT',
  USER = 'USER',
  ROOT = 'ROOT',
}
